apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: aether-ml
  namespace: aether-ml
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["10.96.0.0/16"]
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: aether-ml
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: VCluster
    name: aether-ml
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: aether-ml
  namespace: aether-ml
spec:
  controlPlaneServiceType: ClusterIP
  kubernetesVersion: "1.31.0"
  helmRelease:
    chart:
      name: vcluster
      repo: https://charts.loft.sh
      version: "0.22.1"
    values: |
      sync:
        toHost:
          secrets:
            enabled: true
      networking:
        replicateServices:
          fromHost:
            - from: vault/vault
              to: vault/vault