apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: capi-clusters
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: https://github.com/letDouglas/aether.git
        revision: dev
        directories:
          - path: capi
  template:
    metadata:
      name: "capi-{{ .path.basenameNormalized }}"
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "3"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/letDouglas/aether.git
        targetRevision: dev
        path: "{{ .path.path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      ignoreDifferences:
        - group: infrastructure.cluster.x-k8s.io
          kind: VCluster
          jsonPointers:
            - /spec/controlPlaneEndpoint
            - /spec/kubernetesVersion
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true