apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vso
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault-secrets-operator
      targetRevision: "0.9.1"
      helm:
        releaseName: vso
        valueFiles:
          - $values/clusters/management/vso/values.yaml
    - repoURL: https://github.com/letDouglas/aether.git
      targetRevision: dev
      ref: values
    - repoURL: https://github.com/letDouglas/aether.git
      targetRevision: dev
      path: clusters/management/vso
      directory:
        include: "config.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: vso
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /status/terminatingReplicas