defaultVaultConnection:
  enabled: false

# serviceAccount:
#   create: true
#   name: "vso-vault-secrets-operator-controller-manager"

controller:
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi