image:
  tag: "3.14.0"

backendStore:
  databaseMigration: true
  databaseConnectionCheck: true
  existingDatabaseSecret:
    name: "mlflow-db-creds"
    usernameKey: "username"
    passwordKey: "password"
  postgres:
    enabled: true
    host: "mlflow-db-rw.database.svc.cluster.local"
    port: 5432
    database: "mlflow"
    user: "mlflow"
    password: "DUMMY_OVERRIDE"

artifactRoot:
  s3:
    enabled: true
    bucket: mlflow
    existingSecret:
      name: mlflow-s3-creds
      keyOfAccessKeyId: access-key-id
      keyOfSecretAccessKey: secret-access-key

extraEnvVars:
  MLFLOW_S3_ENDPOINT_URL: http://garage.garage.svc.cluster.local:3900

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
