image:
  tag: "3.14.0"

backendStore:
  databaseMigration: true
  databaseConnectionCheck: true
  postgres:
    enabled: true
    host: "mlflow-db-rw.database.svc.cluster.local"
    port: 5432
    database: "mlflow"
    user: "mlflow"
    password: "DUMMY_OVERRIDE"
    
    existingDatabaseSecret:
      name: "mlflow-db-creds"
      usernameKey: "username"
      passwordKey: "password"

artifactRoot:
  s3:
    enabled: true
    # Internal DNS of the Garage service
    awsS3EndpointUrl: http://garage.garage.svc.cluster.local:3900
    bucket: mlflow
    # These keys match what the Garage Bootstrap job pushed to Vault
    awsAccessKeyIdSecretName: mlflow-s3-creds
    awsAccessKeyIdSecretKey: access-key-id
    awsSecretAccessKeySecretName: mlflow-s3-creds
    awsSecretAccessKeySecretKey: secret-access-key
    region: us-east-1

extraEnvVars:
  MLFLOW_S3_ENDPOINT_URL: http://garage.garage.svc.cluster.local:3900

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
