apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mlflow-db
  namespace: database
spec:
  instances: 1
  storage:
    size: 5Gi
  # CNPG will use the credentials VSO synced from Vault to setup the DB
  bootstrap:
    initdb:
      database: mlflow
      owner: mlflow
      secret:
        name: mlflow-db-creds