apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mlflow-db-secret-sync
  namespace: database
spec:
  vaultAuthRef:
    name: vso-auth
    namespace: vso
  mount: secret
  path: aether/mlflow-db
  type: kv-v2
  destination:
    name: mlflow-db-creds
    create: true