apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-database
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/letDouglas/aether.git
    targetRevision: dev
    path: workloads/database
  destination:
    name: aether-ml
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /status/terminatingReplicas
        - /status/readyReplicas
    - group: postgresql.cnpg.io
      kind: Cluster
      jsonPointers:
        - /status/instancesStatus
        - /status/phase
        - /status/terminatingReplicas
    - group: postgresql.cnpg.io
      kind: Cluster
      jsonPointers:
        - /status/terminatingReplicas
