apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vso-ml
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault-secrets-operator
      targetRevision: "0.9.1"
      helm:
        releaseName: vso-ml
        valueFiles:
          - $values/clusters/ml/vso/values.yaml
    - repoURL: https://github.com/letDouglas/aether.git
      targetRevision: dev
      ref: values
    - repoURL: https://github.com/letDouglas/aether.git
      targetRevision: dev
      path: clusters/ml/vso
      directory:
        include: "config.yaml"
  destination:
    name: aether-ml
    namespace: vso
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true