apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: garage-secret-sync
  namespace: garage
spec:
  # Uses the VaultAuth configured in clusters/ml/vso/config.yaml
  vaultAuthRef: vso-auth
  mount: secret
  path: aether/garage
  type: kv-v2
  destination:
    name: garage-creds
    create: true